site_name: Stakater Documentation
docs_dir: docs
site_url: https://docs.stakater.com/
repo_url: https://github.com/stakater/StakaterCloudDocs
edit_uri: blob/main/docs/

markdown_extensions:
  - attr_list

nav:
  - index.md
