site_name: Stakater Cloud Documentation
docs_dir: docs
site_url: https://docs.stakater.com/
repo_url: https://github.com/stakater/StakaterCloudDocs
edit_uri: blob/main/docs/
use_directory_urls: false
theme:
    name: material
    prev_next_buttons_location: none
    logo: assets/images/favicon.svg
    favicon: assets/images/favicon.svg
    custom_dir: custom_theme/
    palette:
        primary: orange
    features:
        - navigation.tabs

markdown_extensions:
  - attr_list

extra:
    analytics:
        provider: google
        property: G-TTH1YYW5TX
    consent:
        title: Cookie consent
        actions:
            - accept
            - reject
            - manage
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.

nav:
    - Stakater Home: https://www.stakater.com/
    - SAAP: https://www.stakater.com/saap-kubernetes-openshift
    - Consultancy: https://www.stakater.com/kubernetes-consultancy
    - Events: https://www.stakater.com/events
    - Platform Assessment: https://www.stakater.com/kubernetes-platform-assessment
    - Careers: https://www.stakater.com/careers

plugins:
    - search
